In [59]:
from hmenv import *

In [64]:
print(KNN())

Voici mon KNN

In [3]:
import pandas as pd
Train = pd.read_csv("train.csv")
Test = pd.read_csv("test.csv")

In [4]:
Train.head()

,Id,C1,C2,C3,C4,C5,C6,C7,Label
0,1,414.887523,532.710092,671.710972,317.781356,184.736143,78.967907,382.426491,0
1,2,415.887523,533.710092,672.710972,318.781356,184.736143,78.967907,382.426491,0
2,3,425.887523,547.710092,737.710972,358.781356,184.746143,78.967907,382.426491,0
3,4,412.887523,530.710092,657.710972,308.781356,184.736143,78.967907,382.426491,0
4,5,432.887523,554.710092,743.710972,370.781356,184.746143,78.977907,382.426491,0

In [53]:
c = ["C1", "C2", "C3", "C4", "C5", "C6", "C7"] 
X_train = Train[c].to_numpy().tolist()
y_train = Train["Label"].to_numpy().tolist()
Xt = X_train.copy()

X_test = Test[c].to_numpy().tolist()

In [60]:
#données standardisées
X_train_scaled = stdscal(X_train, X_train) 
X_test_scaled = stdscal(X_test, X_train)

In [56]:
model = KNN()
model.fit(X_train_scaled, y_train)
P2 = pd.DataFrame(model.predict(X_test_scaled), columns=["Label"])

In [54]:
P.head()

   Label
0      0
1      0
2      0
3      0
4      0

In [63]:
"""S = pd.concat((Test["Id"], P), axis=1)
S.head()
S.to_csv("Pred0", index=False)"""

In [57]:
P2.head()

   Label
0      0
1      0
2      0
3      0
4      0

In [58]:
S = pd.concat((Test["Id"], P2), axis=1)
S.to_csv("Pred1", index=False)